In [1]:
#import libraries

import numpy as np
import pandas as pd


In [35]:
#import dataset
ds=pd.read_csv("data.csv")
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 452.0+ bytes


In [4]:
#install library
!pip install scikit-learn


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
ds.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [6]:
#handling missing value(using mean and scikit learn)
from sklearn.impute import SimpleImputer
si=SimpleImputer(missing_values = np.nan,strategy='mean')
ds[['Age','Salary']]=si.fit_transform(ds[['Age','Salary']])#double matrix for multiple values


In [7]:
ds

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [8]:
ds["Country"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [9]:
#Encoding categorical column(onehot encoding)
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder(sparse_output=False)#creat variable of OneHotEncoder 
encoded_data=one.fit_transform(ds[["Country"]])
print(encoded_data)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [37]:
#Creating dataframe
column_names=one.get_feature_names_out(["Country"])
encoded_df=pd.DataFrame(encoded_data,columns=column_names)
encoded_df

Country_France  Country_Germany  Country_Spain
0             1.0              0.0            0.0
1             0.0              0.0            1.0
2             0.0              1.0            0.0
3             0.0              0.0            1.0
4             0.0              1.0            0.0
5             1.0              0.0            0.0
6             0.0              0.0            1.0
7             1.0              0.0            0.0
8             0.0              1.0            0.0
9             1.0              0.0            0.0

In [11]:
#getting columns
column_names

array(['Country_France', 'Country_Germany', 'Country_Spain'], dtype=object)

In [12]:
#joining original dataset and new dataframe
ds=pd.concat([ds,encoded_df],axis=1)
ds

Country        Age        Salary Purchased  Country_France  \
0   France  44.000000  72000.000000        No             1.0   
1    Spain  27.000000  48000.000000       Yes             0.0   
2  Germany  30.000000  54000.000000        No             0.0   
3    Spain  38.000000  61000.000000        No             0.0   
4  Germany  40.000000  63777.777778       Yes             0.0   
5   France  35.000000  58000.000000       Yes             1.0   
6    Spain  38.777778  52000.000000        No             0.0   
7   France  48.000000  79000.000000       Yes             1.0   
8  Germany  50.000000  83000.000000        No             0.0   
9   France  37.000000  67000.000000       Yes             1.0   

   Country_Germany  Country_Spain  
0              0.0            0.0  
1              0.0            1.0  
2              1.0            0.0  
3              0.0            1.0  
4              1.0            0.0  
5              0.0            0.0  
6              0.0            1.0  
7              0.0            0.0  
8              1.0            0.0  
9              0.0            0.0

In [13]:
#drop actual categorical country column
ds.drop(columns=["Country"])
ds

Country        Age        Salary Purchased  Country_France  \
0   France  44.000000  72000.000000        No             1.0   
1    Spain  27.000000  48000.000000       Yes             0.0   
2  Germany  30.000000  54000.000000        No             0.0   
3    Spain  38.000000  61000.000000        No             0.0   
4  Germany  40.000000  63777.777778       Yes             0.0   
5   France  35.000000  58000.000000       Yes             1.0   
6    Spain  38.777778  52000.000000        No             0.0   
7   France  48.000000  79000.000000       Yes             1.0   
8  Germany  50.000000  83000.000000        No             0.0   
9   France  37.000000  67000.000000       Yes             1.0   

   Country_Germany  Country_Spain  
0              0.0            0.0  
1              0.0            1.0  
2              1.0            0.0  
3              0.0            1.0  
4              1.0            0.0  
5              0.0            0.0  
6              0.0            1.0  
7              0.0            0.0  
8              1.0            0.0  
9              0.0            0.0

In [15]:
#Label encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
ds['Purchased']=le.fit_transform(ds['Purchased'])

In [16]:
ds

Country        Age        Salary  Purchased  Country_France  \
0   France  44.000000  72000.000000          0             1.0   
1    Spain  27.000000  48000.000000          1             0.0   
2  Germany  30.000000  54000.000000          0             0.0   
3    Spain  38.000000  61000.000000          0             0.0   
4  Germany  40.000000  63777.777778          1             0.0   
5   France  35.000000  58000.000000          1             1.0   
6    Spain  38.777778  52000.000000          0             0.0   
7   France  48.000000  79000.000000          1             1.0   
8  Germany  50.000000  83000.000000          0             0.0   
9   France  37.000000  67000.000000          1             1.0   

   Country_Germany  Country_Spain  
0              0.0            0.0  
1              0.0            1.0  
2              1.0            0.0  
3              0.0            1.0  
4              1.0            0.0  
5              0.0            0.0  
6              0.0            1.0  
7              0.0            0.0  
8              1.0            0.0  
9              0.0            0.0

In [17]:
#Feature Scaling(Reduce Large data values to its smaller datavalues)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
ds[['Age','Salary']]=sc.fit_transform(ds[['Age','Salary']])

In [27]:
#divide dataset into independent(input and dependent(output)variables
x=ds[['Age','Salary','Country_France','Country_Germany','Country_Spain']]
y=ds[['Purchased']]


In [28]:
x

Age        Salary  Country_France  Country_Germany  Country_Spain
0  0.758874  7.494733e-01             1.0              0.0            0.0
1 -1.711504 -1.438178e+00             0.0              0.0            1.0
2 -1.275555 -8.912655e-01             0.0              1.0            0.0
3 -0.113024 -2.532004e-01             0.0              0.0            1.0
4  0.177609  6.632192e-16             0.0              1.0            0.0
5 -0.548973 -5.266569e-01             1.0              0.0            0.0
6  0.000000 -1.073570e+00             0.0              0.0            1.0
7  1.340140  1.387538e+00             1.0              0.0            0.0
8  1.630773  1.752147e+00             0.0              1.0            0.0
9 -0.258340  2.937125e-01             1.0              0.0            0.0

In [29]:
y

Purchased
0          0
1          1
2          0
3          0
4          1
5          1
6          0
7          1
8          0
9          1

In [30]:
#spliting dataset as Training and testing

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [31]:
x_train

Age        Salary  Country_France  Country_Germany  Country_Spain
6  0.000000 -1.073570e+00             0.0              0.0            1.0
4  0.177609  6.632192e-16             0.0              1.0            0.0
0  0.758874  7.494733e-01             1.0              0.0            0.0
3 -0.113024 -2.532004e-01             0.0              0.0            1.0
1 -1.711504 -1.438178e+00             0.0              0.0            1.0
7  1.340140  1.387538e+00             1.0              0.0            0.0
8  1.630773  1.752147e+00             0.0              1.0            0.0
5 -0.548973 -5.266569e-01             1.0              0.0            0.0

In [32]:
x_test

Age    Salary  Country_France  Country_Germany  Country_Spain
2 -1.275555 -0.891265             0.0              1.0            0.0
9 -0.258340  0.293712             1.0              0.0            0.0

In [33]:
y_train


Purchased
6          0
4          1
0          0
3          0
1          1
7          1
8          0
5          1

In [34]:
y_test

Purchased
2          0
9          1

In [38]:
#practice to see other result
#spliting dataset as Training and testing

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,random_state=2)

In [40]:
x_train

Age    Salary  Country_France  Country_Germany  Country_Spain
2 -1.275555 -0.891265             0.0              1.0            0.0
3 -0.113024 -0.253200             0.0              0.0            1.0
6  0.000000 -1.073570             0.0              0.0            1.0
9 -0.258340  0.293712             1.0              0.0            0.0
8  1.630773  1.752147             0.0              1.0            0.0

In [41]:
x_test

Age        Salary  Country_France  Country_Germany  Country_Spain
4  0.177609  6.632192e-16             0.0              1.0            0.0
1 -1.711504 -1.438178e+00             0.0              0.0            1.0
5 -0.548973 -5.266569e-01             1.0              0.0            0.0
0  0.758874  7.494733e-01             1.0              0.0            0.0
7  1.340140  1.387538e+00             1.0              0.0            0.0

In [42]:
y_train

Purchased
2          0
3          0
6          0
9          1
8          0

In [43]:
y_test

Purchased
4          1
1          1
5          1
0          0
7          1