In [1]:
#import libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#import dataset
ds=pd.read_csv("raw_messy_dataset.csv")
ds.head(10)

Name      Age  Gender              Email     Join_Date Salary  \
0    Alice      NaN     NaN  user0@example.com    2021-05-21    NaN   
1      Bob       40       M  user1@example.com           NaN  50000   
2  Charlie  unknown    Male  user2@example.com    2020/01/01  50000   
3    David      NaN     NaN  user3@example.com    2021-05-21  70000   
4      Eva       35   Other  user4@example.com  July 4, 2020  70000   
5    Frank  unknown   Other  user5@example.com           NaN  70000   
6    Grace  unknown  Female  user6@example.com  July 4, 2020  80000   
7   Hannah      NaN   Other  user7@example.com    2021-05-21    NaN   
8      Ivy       30  Female  user8@example.com           NaN  50000   
9     Jack       35    Male  user9@example.com    2020/01/01  80000   

    Department  
0        Admin  
1  Engineering  
2           HR  
3        Admin  
4  Engineering  
5        Admin  
6  Engineering  
7           HR  
8  Engineering  
9  Engineering

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        105 non-null    object
 1   Age         72 non-null     object
 2   Gender      89 non-null     object
 3   Email       95 non-null     object
 4   Join_Date   70 non-null     object
 5   Salary      78 non-null     object
 6   Department  89 non-null     object
dtypes: object(7)
memory usage: 5.9+ KB


In [4]:
ds.describe()

Name Age Gender              Email   Join_Date Salary   Department
count     105  72     89                 95          70     78           89
unique     10   5      5                 90           4      5            5
top     Alice  40   Male  user0@example.com  2021-05-21  50000  Engineering
freq       11  22     22                  2          26     22           26

In [8]:
#searching for duplications
ds.duplicated().sum()

np.int64(0)

In [7]:
#Remove duplications
ds.drop_duplicates(inplace=True)

In [9]:
#to get header of colums
ds.columns

Index(['Name', 'Age', 'Gender', 'Email', 'Join_Date', 'Salary', 'Department'], dtype='object')

In [11]:
#Handling age
ds["Age"]=pd.to_numeric(ds["Age"],errors='coerce')


In [15]:
ds["Age"].unique()

array([35., 40., 30., 25.])

In [12]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        100 non-null    object 
 1   Age         57 non-null     float64
 2   Gender      86 non-null     object 
 3   Email       90 non-null     object 
 4   Join_Date   66 non-null     object 
 5   Salary      74 non-null     object 
 6   Department  84 non-null     object 
dtypes: float64(1), object(6)
memory usage: 6.2+ KB


In [13]:
#to fill missing values
x=ds["Age"].median()
ds["Age"].fillna(x,inplace=True)

C:\Users\mayup\AppData\Local\Temp\ipykernel_14156\4230202996.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds["Age"].fillna(x,inplace=True)


In [14]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        100 non-null    object 
 1   Age         100 non-null    float64
 2   Gender      86 non-null     object 
 3   Email       90 non-null     object 
 4   Join_Date   66 non-null     object 
 5   Salary      74 non-null     object 
 6   Department  84 non-null     object 
dtypes: float64(1), object(6)
memory usage: 6.2+ KB


In [16]:
ds["Gender"].unique()

array([nan, 'M', 'Male', 'Other', 'Female', 'F'], dtype=object)

In [19]:
ds["Gender"]=ds["Gender"].replace({
    "M":"Male","F":"Female","":"None"
})
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Name        100 non-null    object 
 1   Age         100 non-null    float64
 2   Gender      86 non-null     object 
 3   Email       90 non-null     object 
 4   Join_Date   66 non-null     object 
 5   Salary      74 non-null     object 
 6   Department  84 non-null     object 
dtypes: float64(1), object(6)
memory usage: 6.2+ KB


In [20]:
ds["Gender"].unique()

array([nan, 'Male', 'Other', 'Female'], dtype=object)

In [21]:
#Handling empty colums
ds["Email"].fillna("None",inplace=True)

C:\Users\mayup\AppData\Local\Temp\ipykernel_14156\4181753720.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds["Email"].fillna("None",inplace=True)


In [22]:
print(ds.to_string())


       Name   Age  Gender               Email     Join_Date   Salary   Department
0     Alice  35.0     NaN   user0@example.com    2021-05-21      NaN        Admin
1       Bob  40.0    Male   user1@example.com           NaN    50000  Engineering
2   Charlie  35.0    Male   user2@example.com    2020/01/01    50000           HR
3     David  35.0     NaN   user3@example.com    2021-05-21    70000        Admin
4       Eva  35.0   Other   user4@example.com  July 4, 2020    70000  Engineering
5     Frank  35.0   Other   user5@example.com           NaN    70000        Admin
6     Grace  35.0  Female   user6@example.com  July 4, 2020    80000  Engineering
7    Hannah  35.0   Other   user7@example.com    2021-05-21      NaN           HR
8       Ivy  30.0  Female   user8@example.com           NaN    50000  Engineering
9      Jack  35.0    Male   user9@example.com    2020/01/01    80000  Engineering
10    Alice  35.0    Male  user10@example.com    2021-05-21    70000  Engineering
11      Bob  35.

In [25]:
#handling data column
ds["join_date"]=pd.to_datetime(ds["Join_Date"],errors="coerce")
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   Name        100 non-null    object        
 1   Age         100 non-null    float64       
 2   Gender      86 non-null     object        
 3   Email       100 non-null    object        
 4   Join_Date   66 non-null     object        
 5   Salary      74 non-null     object        
 6   Department  84 non-null     object        
 7   join_date   24 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 7.0+ KB


In [26]:
#handling salary columns
ds["Salary"]=pd.to_numeric(ds["Salary"],errors="coerce")
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   Name        100 non-null    object        
 1   Age         100 non-null    float64       
 2   Gender      86 non-null     object        
 3   Email       100 non-null    object        
 4   Join_Date   66 non-null     object        
 5   Salary      60 non-null     float64       
 6   Department  84 non-null     object        
 7   join_date   24 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 7.0+ KB


In [27]:
#handling department column
ds["Department"].unique()


array(['Admin', 'Engineering', 'HR', 'Sales', nan, 'Marketing'],
      dtype=object)

In [31]:
y=ds["Department"].mode()[0]
ds["Department"].fillna(y,inplace=True)
ds.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   Name        100 non-null    object        
 1   Age         100 non-null    float64       
 2   Gender      86 non-null     object        
 3   Email       100 non-null    object        
 4   Join_Date   66 non-null     object        
 5   Salary      60 non-null     float64       
 6   Department  100 non-null    object        
 7   join_date   24 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 7.0+ KB


C:\Users\mayup\AppData\Local\Temp\ipykernel_14156\4258210176.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  ds["Department"].fillna(y,inplace=True)


In [34]:
#save data into new file

ds.to_csv("cleaned_data.csv")